# Generated by Django 4.1.4 on 2022-12-23 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formatted_datetime", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=150)),
                ("excerpt", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(
                        verbose_name=django.core.validators.MinLengthValidator(50)
                    ),
                ),
            ],
        ),
    ]
