# Generated by Django 4.1.4 on 2022-12-23 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("excerpt", models.CharField(max_length=200)),
                ("image_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="timelineentry",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(50)]
            ),
        ),
    ]
