# Generated by Django 4.1.4 on 2022-12-26 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_skill_alter_timelineentry_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="excerpt",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(61)],
            ),
        ),
    ]
