# Generated by Django 4.1.4 on 2022-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_alter_timelineentry_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineentry",
            name="excerpt",
            field=models.CharField(max_length=200),
        ),
    ]
