# Generated by Django 4.1.4 on 2022-12-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_timelineentry_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineentry",
            name="order_number",
            field=models.IntegerField(null=True),
        ),
    ]
