# Generated by Django 4.1.4 on 2022-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="post",
            name="excerpt",
        ),
        migrations.AddField(
            model_name="post",
            name="blog_link",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
