# Generated by Django 4.1.4 on 2022-12-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
