# Generated by Django 4.1.4 on 2022-12-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_size",
            field=models.CharField(default="15rem", max_length=6),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="blog.category"),
        ),
    ]
