# Generated by Django 4.1.4 on 2022-12-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_image_size_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_size",
            field=models.CharField(default="12rem", max_length=6),
        ),
    ]
