# Generated by Django 4.1.4 on 2022-12-26 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_image_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(
                max_length=100,
                null=True,
                validators=[django.core.validators.MinLengthValidator(61)],
            ),
        ),
    ]
