# Generated by Django 4.1.4 on 2022-12-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="project",
            name="image_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="youtube_link",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
