# Generated by Django 4.1.4 on 2022-12-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_published_quarter_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
