# Generated by Django 4.1.4 on 2022-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
