name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Generate requirements.txt
        run: poetry export -f requirements.txt -o requirements.txt
      - name: List files
        run: ls